"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 5.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-zl6=raa$xckx^#fxy22^=4dflntp==zzj7(vut8%ebfk4%e2_c'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["agroapi-qwvb.onrender.com","127.0.0.1","localhost"]


# Application definition

INSTALLED_APPS = [
    'jazzmin',

    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
     # Django REST Framework
     'corsheaders',
    'rest_framework',
     'django_filters',
    # Notre application API
    'api',
    
    
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    "whitenoise.middleware.WhiteNoiseMiddleware",
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'corsheaders.middleware.CorsMiddleware',
]

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'fr'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / "staticfiles"

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
CORS_ALLOWED_ORIGINS = [
    ' http://localhost:5173', 
    'https://agromarket-3rdp.onrender.com'
     # C'est l'URL par défaut pour React en mode développement
]
REST_FRAMEWORK = {
    
    'DEFAULT_FILTER_BACKENDS': ['django_filters.rest_framework.DjangoFilterBackend'],
}
JAZZMIN_SETTINGS = {
     "site_brand": "Agrimarket",
    "site_title": "Suivi Prix Marché Admin",  # Titre du site
    "site_header": "IGOTECH Dashboard",       # En-tête
    "welcome_sign": "Bienvenue dans l'administration Suivi Prix Marché",
    "show_sidebar": True,                    # Afficher la barre latérale
    "navigation_expanded": True,             # Dérouler le menu
    "icons": {                               # Icônes personnalisées pour tes modèles
        "produits.Produit": "fas fa-boxes",
        "utilisateurs.Utilisateur": "fas fa-user",
    },
    "custom_links": {                        # Liens personnalisés dans l'admin
        "produits": [{
            "name": "Produits populaires",
            "url": "produits/populaires/",
            "icon": "fas fa-chart-line",
            "permissions": ["produits.view_produit"]
        }]
    },
    "topmenu_links": [                       # Liens dans le menu supérieur
        {"name": "Accueil", "url": "/", "permissions": ["auth.view_user"]},
        {"name": "Documentation", "url": "https://encour", "new_window": True},
    ],
                    # Active l'éditeur d'interface
}
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'
# Configuration du stockage des fichiers
STORAGES = {
    "default": {  # Pour les fichiers média (uploads)
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {  # Pour les fichiers statiques (CSS, JS)
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

# Configuration des fichiers média
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'